.TH PHO l "June 28 2002" "PHO"
.SH NAME
\fBpho\fP \- View and annotate multiple images
.SH SYNTAX
.B pho
.RI [ options ]
.RI [ filename [ filename... ]]
.SH DESCRIPTION
.I pho
displays images, in the formats handled by the
.IR gdk-pixbuf
package, to an X display.
It is intended as a lightweight and fast viewer,
optimized for rapidly going through large numbers of uploaded images.
.PP
.I pho
is entirely keyboard driven,
and allows for interactive rotation and taking of notes on each image.
It resizes after rotations and will always attempt to show
the image as large as possible.  The final rotation reached for
each image will be remembered and printed when the program exits
(for use with a batch image rotation script).
.PP
.I pho
can also remember up to ten lists of images (numbered 0-9) which can
correspond to anything the user wishes, plus a list of images to be
deleted.
\fIpho\fR currently does not actually change any files on disk.
.SH COMMAND-LINE OPTIONS
.TP
\fB\-d\fR
Debug mode: may print a few debugging messages to standard output.
.TP
\fB\-v, -h\fR
Print version and usage info, and exit.
.SH KEY BINDINGS
When pho is running, it obeys the following keys:
.TP
\fB[space]\fR
Go to next image
.TP
\fB[backspace]\fR, \fB-\fR
Go to previous image
.TP
\fBr\fR, \fBt\fR, \fB[right-arrow]\fR
Rotate right (clockwise)
.TP
\fBR\fR, \fBT\fR, \fBl\fR, \fBL\fR, \fB[left-arrow]\fR
Rotate left (counter-clockwise)
.TP
\fB[up-arrow]\fR
Rotate 180 degrees.
.TP
\fBHome\fR
Go back to the first image.
.TP
\fBd\fR
Delete (will bring up a confirmation dialog; clicking OK or
typing another d deletes the file).
.TP
\fBi\fR
Bring up an information dialog.
.TP
\fB0\fR through \fB9\fR
Add the image to the appropriate notes list
.TP
\fBf\fR
Toggle in/out of "full screen mode".
Images will be scaled up to fill the screen in at least one dimension.
.TP
\fBp\fR
Toggle in/out of "presentation mode".
If the window manager permits, pho will take up the full screen
with the image (if smaller) centered.
.TP
\fBF\fR
Toggle in/out of "full size mode".  Images will be shown at their
native size, even if it's bigger than the screen size.
(Hint: Many window managers let you move oversized windows with alt-drag.)
.TP
\fB+\fR, \fB=\fR Magnify: show the image at twice the current size.
.TP
\fB/\fR, \fB<keypad>-\fR Unmagnify: show the image at half the current size.
.TP
\fBq\fR
Quit
.SH AUTHOR
Akkana Peck
.SH COPYRIGHT
Copyright \(co 2002, 2003, 2004 Akkana Peck
.br
Pho is free software, licensed under the GNU Public License.
.SH SEE ALSO
The most recent version of \fIpho\fR, and more information about it, is at:
http://www.shallowsky.com/software/pho.html
